<a href="https://colab.research.google.com/github/yatharth-mishra/city-mood-analytics/blob/main/01_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd

# Load dataset
url = "https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv"
df = pd.read_csv(url)

# Info about columns and missing data
print("Column types and missing data:")
df.info()

# Statistical summary
print("\nStatistical summary:")
display(df.describe())

# All column names
print("\nAll column names:")
print(df.columns.tolist())

# Preview first few rows
print("\nPreview first 5 rows:")
display(df.head())

Column types and missing data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50191 entries, 0 to 50190
Data columns (total 79 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   country                                    50191 non-null  object
 1   year                                       50191 non-null  int64
 2   iso_code                                   42262 non-null  object
 3   population                                 41019 non-null  float64
 4   gdp                                        15251 non-null  float64
 5   cement_co2                                 28863 non-null  float64
 6   cement_co2_per_capita                      25358 non-null  float64
 7   co2                                        29137 non-null  float64
 8   co2_growth_abs                             26981 non-null  float64
 9   co2_growth_prct                            26002 non-null  float64
 10  co2_including_luc                          23585 non-null  float64
 11  co2_including_luc_growth_abs               23285 non-null  float64
 12  co2_including_luc_growth_prct              23285 non-null  float64
 13  co2_including_luc_per_capita               23495 non-null  float64
 14  co2_including_luc_per_gdp                  16790 non-null  float64
 15  co2_including_luc_per_unit_energy          9701 non-null   float64
 16  co2_per_capita                             26182 non-null  float64
 17  co2_per_gdp                                17528 non-null  float64
 18  co2_per_unit_energy                        10350 non-null  float64
 19  coal_co2                                   21755 non-null  float64
 20  coal_co2_per_capita                        21050 non-null  float64
 21  consumption_co2                            4866 non-null   float64
 22  consumption_co2_per_capita                 4502 non-null   float64
 23  consumption_co2_per_gdp                    4444 non-null   float64
 24  cumulative_cement_co2                      28841 non-null  float64
 25  cumulative_co2                             27328 non-null  float64
 26  cumulative_co2_including_luc               23585 non-null  float64
 27  cumulative_coal_co2                        21755 non-null  float64
 28  cumulative_flaring_co2                     15891 non-null  float64
 29  cumulative_gas_co2                         18014 non-null  float64
 30  cumulative_luc_co2                         37236 non-null  float64
 31  cumulative_oil_co2                         25217 non-null  float64
 32  cumulative_other_co2                       3202 non-null   float64
 33  energy_per_capita                          10109 non-null  float64
 34  energy_per_gdp                             7696 non-null   float64
 35  flaring_co2                                15952 non-null  float64
 36  flaring_co2_per_capita                     14694 non-null  float64
 37  gas_co2                                    18014 non-null  float64
 38  gas_co2_per_capita                         17292 non-null  float64
 39  ghg_excluding_lucf_per_capita              35639 non-null  float64
 40  ghg_per_capita                             35813 non-null  float64
 41  land_use_change_co2                        37236 non-null  float64
 42  land_use_change_co2_per_capita             36434 non-null  float64
 43  methane                                    37410 non-null  float64
 44  methane_per_capita                         35813 non-null  float64
 45  nitrous_oxide                              38280 non-null  float64
 46  nitrous_oxide_per_capita                   36320 non-null  float64
 47  oil_co2                                    25218 non-null  float64
 48  oil_co2_per_capita                         24436 non-null  float64
 49  other_co2_per_capita                       2474 non-null   float64
 50  other_industry_co2                         3202 non-null   float64
 51  primary_energy_consumption                 10151 non-null  float64
 52  share_global_cement_co2                    21960 non-null  float64
 53  share_global_co2                           27328 non-null  float64
 54  share_global_co2_including_luc             23585 non-null  float64
 55  share_global_coal_co2                      21755 non-null  float64
 56  share_global_cumulative_cement_co2         21960 non-null  float64
 57  share_global_cumulative_co2                27328 non-null  float64
 58  share_global_cumulative_co2_including_luc  23585 non-null  float64
 59  share_global_cumulative_coal_co2           21755 non-null  float64
 60  share_global_cumulative_flaring_co2        10869 non-null  float64
 61  share_global_cumulative_gas_co2            15034 non-null  float64
 62  share_global_cumulative_luc_co2            37236 non-null  float64
 63  share_global_cumulative_oil_co2            23592 non-null  float64
 64  share_global_cumulative_other_co2          2108 non-null   float64
 65  share_global_flaring_co2                   10869 non-null  float64
 66  share_global_gas_co2                       15034 non-null  float64
 67  share_global_luc_co2                       37236 non-null  float64
 68  share_global_oil_co2                       23592 non-null  float64
 69  share_global_other_co2                     2108 non-null   float64
 70  share_of_temperature_change_from_ghg       41001 non-null  float64
 71  temperature_change_from_ch4                38060 non-null  float64
 72  temperature_change_from_co2                41001 non-null  float64
 73  temperature_change_from_ghg                41001 non-null  float64
 74  temperature_change_from_n2o                38060 non-null  float64
 75  total_ghg                                  37410 non-null  float64
 76  total_ghg_excluding_lucf                   37236 non-null  float64
 77  trade_co2                                  4535 non-null   float64
 78  trade_co2_share                            4535 non-null   float64
dtypes: float64(76), int64(1), object(2)
memory usage: 30.3+ MB

Statistical summary:

,year,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,co2_including_luc,co2_including_luc_growth_abs,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
count,50191.000000,4.101900e+04,1.525100e+04,28863.000000,25358.000000,29137.000000,26981.000000,26002.000000,23585.000000,23285.000000,...,2108.000000,41001.000000,38060.000000,41001.000000,41001.000000,38060.000000,37410.000000,37236.000000,4535.000000,4535.000000
mean,1919.883067,5.686141e+07,3.300495e+11,7.767746,0.059036,415.698178,6.208882,43.104462,535.581202,7.214604,...,7.512655,2.269285,0.003026,0.007670,0.011023,0.000509,488.542225,316.133529,-7.232399,20.524440
std,65.627296,3.199905e+08,3.086383e+12,62.595292,0.120328,1945.843973,62.322553,1729.939596,2202.219657,99.347980,...,17.671054,9.315325,0.016519,0.043694,0.061901,0.003043,2392.579910,1839.602293,250.640012,52.744956
min,1750.000000,2.150000e+02,4.998000e+07,0.000000,0.000000,0.000000,-1977.750000,-100.000000,-99.693000,-2325.500000,...,0.000000,-0.810000,-0.001000,0.000000,-0.001000,0.000000,-14.961000,0.000000,-2195.952000,-98.849000
25%,1875.000000,3.273130e+05,7.874038e+09,0.000000,0.000000,0.374000,-0.005000,-1.102500,6.418000,-0.908000,...,0.204750,0.004000,0.000000,0.000000,0.000000,0.000000,1.835000,0.235000,-3.179500,-6.168000
50%,1924.000000,2.289522e+06,2.743861e+10,0.000000,0.001000,4.990000,0.044000,3.803500,27.691000,0.078000,...,0.838000,0.078000,0.000000,0.000000,0.000000,0.000000,15.007500,2.371000,1.518000,8.701000
75%,1974.000000,9.862459e+06,1.212627e+11,0.486000,0.075750,53.273000,1.002000,10.890750,123.959000,2.620000,...,3.211000,0.359000,0.001000,0.001000,0.001000,0.000000,78.242750,29.337500,9.153500,32.666000
max,2023.000000,8.091735e+09,1.301126e+14,1696.308000,2.484000,37791.570000,1865.208000,180870.000000,41416.480000,2340.184000,...,100.000000,100.000000,0.422000,1.161000,1.668000,0.085000,53816.852000,44114.785000,1798.999000,568.635000

All column names:
['country', 'year', 'iso_code', 'population', 'gdp', 'cement_co2', 'cement_co2_per_capita', 'co2', 'co2_growth_abs', 'co2_growth_prct', 'co2_including_luc', 'co2_including_luc_growth_abs', 'co2_including_luc_growth_prct', 'co2_including_luc_per_capita', 'co2_including_luc_per_gdp', 'co2_including_luc_per_unit_energy', 'co2_per_capita', 'co2_per_gdp', 'co2_per_unit_energy', 'coal_co2', 'coal_co2_per_capita', 'consumption_co2', 'consumption_co2_per_capita', 'consumption_co2_per_gdp', 'cumulative_cement_co2', 'cumulative_co2', 'cumulative_co2_including_luc', 'cumulative_coal_co2', 'cumulative_flaring_co2', 'cumulative_gas_co2', 'cumulative_luc_co2', 'cumulative_oil_co2', 'cumulative_other_co2', 'energy_per_capita', 'energy_per_gdp', 'flaring_co2', 'flaring_co2_per_capita', 'gas_co2', 'gas_co2_per_capita', 'ghg_excluding_lucf_per_capita', 'ghg_per_capita', 'land_use_change_co2', 'land_use_change_co2_per_capita', 'methane', 'methane_per_capita', 'nitrous_oxide', 'nitrous_oxide_per_capita', 'oil_co2', 'oil_co2_per_capita', 'other_co2_per_capita', 'other_industry_co2', 'primary_energy_consumption', 'share_global_cement_co2', 'share_global_co2', 'share_global_co2_including_luc', 'share_global_coal_co2', 'share_global_cumulative_cement_co2', 'share_global_cumulative_co2', 'share_global_cumulative_co2_including_luc', 'share_global_cumulative_coal_co2', 'share_global_cumulative_flaring_co2', 'share_global_cumulative_gas_co2', 'share_global_cumulative_luc_co2', 'share_global_cumulative_oil_co2', 'share_global_cumulative_other_co2', 'share_global_flaring_co2', 'share_global_gas_co2', 'share_global_luc_co2', 'share_global_oil_co2', 'share_global_other_co2', 'share_of_temperature_change_from_ghg', 'temperature_change_from_ch4', 'temperature_change_from_co2', 'temperature_change_from_ghg', 'temperature_change_from_n2o', 'total_ghg', 'total_ghg_excluding_lucf', 'trade_co2', 'trade_co2_share']

Preview first 5 rows:

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
0,Afghanistan,1750,AFG,2802560.0,NaN,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1751,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1752,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1753,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1754,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
ag_df = df[df['country'] == 'Afghanistan'] # Afghanistan Data Frame
display(ag_df.head())
display(ag_df.tail())

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
0,Afghanistan,1750,AFG,2802560.0,NaN,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1751,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1752,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1753,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1754,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
269,Afghanistan,2019,AFG,37856126.0,7.308571e+10,0.038,0.001,10.825,0.223,2.106,...,NaN,0.083,0.001,0.001,0.001,0.0,39.145,18.538,NaN,NaN
270,Afghanistan,2020,AFG,39068978.0,7.141771e+10,0.061,0.002,11.606,0.781,7.213,...,NaN,0.083,0.001,0.001,0.001,0.0,37.833,18.633,NaN,NaN
271,Afghanistan,2021,AFG,40000411.0,5.663885e+10,0.016,0.000,10.272,-1.334,-11.495,...,NaN,0.084,0.001,0.001,0.001,0.0,38.313,17.947,NaN,NaN
272,Afghanistan,2022,AFG,40578846.0,5.330347e+10,0.016,0.000,10.558,0.286,2.784,...,NaN,0.084,0.001,0.001,0.001,0.0,39.485,18.355,NaN,NaN
273,Afghanistan,2023,AFG,41454762.0,NaN,0.016,0.000,11.020,0.462,4.380,...,NaN,0.084,0.001,0.001,0.001,0.0,40.081,18.638,NaN,NaN

In [25]:
columns_to_keep = [
    "country", "year", "population", "gdp", "co2", "co2_per_capita",
    "coal_co2", "oil_co2", "gas_co2", "cement_co2"
]

# Keep only existing columns
columns_to_keep_existing = [col for col in columns_to_keep if col in df.columns]
df = df[columns_to_keep_existing]

# Calculate gdp_per_capita
df['gdp_per_capita'] = df['gdp'] / df['population']

In [26]:
# Check missing values
print(df.isnull().sum())

# Fill CO2 per capita missing values with 0 (or drop if needed)
df['co2_per_capita'].fillna(0, inplace=True)

# Drop rows without country or year
df.dropna(subset=['country', 'year'], inplace=True)

country               0
year                  0
population         9172
gdp               34940
co2               21054
co2_per_capita    24009
gdp_per_capita    34940
dtype: int64

/tmp/ipython-input-3159467280.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['co2_per_capita'].fillna(0, inplace=True)